lang: es
bibliography: references.bib

project:
  type: book

book:
  title: "Visualización de Datos"
  author: "Carolina Bonifacino"

  chapters:
    - index.qmd

    - part: "Fundamentos"
      chapters:
        - capitulos/01-fundamentos/01-introduccion.qmd
        - capitulos/01-fundamentos/02-tipos-de-datos.qmd

    - part: "Gráficos"
      chapters:
        - capitulos/02-graficos/01-elegir-grafico.qmd
        - capitulos/02-graficos/02-comparacion.qmd

    - references.qmd

format:
  html:
    theme: cosmo
    css: styles.css

  pdf:
    documentclass: scrreprt

  epub:
    toc: true